on:
  workflow_dispatch:
jobs:
  benchmark:
    runs-on: ubuntu-latest
    env:
      BORG_LIBDEFLATE_PREFIX: /usr
    steps:
    - name: Install hyperfine
      run: |
        wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
        sudo dpkg -i hyperfine_1.13.0_amd64.deb
    - uses: actions/checkout@v3
      with:
        # just fetching 1 commit is not enough for setuptools-scm, so we fetch all
        fetch-depth: 0
    - uses: actions/setup-python@v3.0.0
    - name: Install native deps
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config build-essential
        sudo apt-get install -y libssl-dev libacl1-dev libxxhash-dev libdeflate-dev liblz4-dev libzstd-dev
        sudo apt-get install -y libfuse-dev fuse || true  # Required for Python llfuse module
        sudo apt-get install -y libfuse3-dev fuse3 || true  # Required for Python pyfuse3 module
    - run: pip install -r requirements.d/development.txt
    - run: pip install -e .
    - run: |
        COMMON=(pytest src/borg/testsuite/{archiver,benchmark,cache,crypto,key,remote}.py)
        hyperfine --ignore-failure --warmup 1 --runs 5 "BORG_TESTONLY_MOCK_KDF=1 ${COMMON[*]}" "${COMMON[*]}"
